VIAL_ENABLE = yes
QMK_SETTINGS = yes
DYNAMIC_KEYMAP_ENABLE = yes

# Enable all QMK settings in Vial
VIALRGB_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
AUTOSHIFT_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
